import pytest
from tests.fixtures.code_fixture_java import java_code_fixture
from tests.fixtures.code_fixture_py import python_code_fixture
from tests.fixtures.code_fixture_js import javascript_code_fixture
